import React, { useState, useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ethers } from "ethers";

import { contatoreAddress } from "../contatoreV3Config";

import ContatoreV3 from "../artifacts/contracts/ContatoreV3.sol/ContatoreV3.json";

export default function Home() {
  const [contract, setContract] = useState();
  const [amount, setAmount] = useState();
  useEffect(() => onLoad(), []);

  useEffect(() => console.log("Contract", contract), [contract]);

  const onLoad = () => {
    getContract();
  };

  const getContract = () => {
    if (typeof window.ethereum === "undefined") return;
    const provider = new ethers.providers.Web3Provider(window.ethereum);
    const signer = provider.getSigner();
    const localContract = new ethers.Contract(
      contatoreAddress,
      ContatoreV3.abi,
      signer
    );
    setContract(localContract);
  };

  const onClick = async () => {
    try {
      let transaction = await contract.increaseValue(1);
      await transaction.wait();
      getX();
      console.log("Increased!");
    } catch (err) {
      console.log("Error:", err);
    }
  };

  const onClickDecrease = async () => {
    try {
      let transaction = await contract.decreaseValue(1);
      await transaction.wait();
      getX();
      console.log("Decreased!");
    } catch (err) {
      console.log("Error:", err);
    }
  }

  const getX = async () => {
    await contract.x().then((result) => setAmount(result.toString()));
  };

  useEffect(() => {
    if (contract == undefined) return;
    try {
      getX();
    } catch (err) {
      console.log("Error: ", err);
    }
  }, [contract]);

  if (contract === undefined) return "Loading...";
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>Welcome to OZ Upgradeable Contract</h2>

        <div className={styles.grid}>Counter: {amount}</div>

        <div className={styles.grid}>
          <button onClick={onClick}> + increase </button>
        </div>

        <div className={styles.grid}>
          <button onClick={onClickDecrease}> - decrease </button>
        </div>
      </main>

      <footer className={styles.footer}>
        Made with love by <strong>Lawis SRL</strong>
      </footer>
    </div>
  );
}
