import React, { useState, useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ethers } from "ethers";

import { contatoreAddress } from "../contatoreConfig";

import Contatore from "../artifacts/contracts/Contatore.sol/Contatore.json";

export default function Home() {
  const [contract, setContract] = useState();

  useEffect(() => onLoad(), []);

  const onLoad = () => {
    getContract();
  };

  const getContract = async () => {
    if (typeof window.ethereum === "undefined") return;
    const provider = new ethers.providers.Web3Provider(window.ethereum);
    const signer = provider.getSigner();
    setContract(new ethers.Contract(contatoreAddress, Contatore.abi, signer));
    console.log("Add Contract: ", contract)
  };

  const onClick = async () => {
    try{
      let transaction = await contract.increaseValue();
      await transaction.wait();
      console.log("Increased!")
    }catch(err){
      console.log("Error:",err)
    }
  }

  if (contract === undefined) return "Loading...";
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to OZ Upgradeable Contract
        </h1>

        <div className={styles.grid}>
          Counter: {contract.x}
        </div>

        <div className={styles.grid}>
          <button onClick={onClick}> + increase </button>
        </div>
      </main>

      <footer className={styles.footer}>
        Made with love by <strong>Lawis SRL</strong>
      </footer>
    </div>
  );
}
